"""initial_migration

Revision ID: 07632ec31958
Revises: 
Create Date: 2026-03-01 12:27:41.711798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07632ec31958'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.String(length=36), nullable=False),
    sa.Column('acao', sa.String(length=10), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('dados_antigos', sa.JSON(), nullable=True),
    sa.Column('dados_novos', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_registro_id'), 'audit_logs', ['registro_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tabela'), 'audit_logs', ['tabela'], unique=False)
    op.create_table('cartoes_credito',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('dia_fechamento', sa.Integer(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('limite', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('centros_custo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA', name='tipolancamento'), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['centros_custo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('participantes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('documento', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('CLIENTE', 'FORNECEDOR', 'AMBOS', name='tipoparticipante'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participantes_documento'), 'participantes', ['documento'], unique=True)
    op.create_index(op.f('ix_participantes_nome'), 'participantes', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('secret_2fa', sa.String(length=64), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('processos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('numero_cnj', sa.String(length=30), nullable=True),
    sa.Column('titulo_causa', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('percentual_exito', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_pro_labore', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_causa_atualizado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_causa_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'SUSPENSO', 'ENCERRADO', 'TRANSITO_JULGADO', name='statusprocesso'), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cnj')
    )
    op.create_index(op.f('ix_processos_numero'), 'processos', ['numero'], unique=True)
    op.create_table('lancamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_realizado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_previsto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA', name='tipolancamento'), nullable=False),
    sa.Column('natureza', sa.Enum('FIXO', 'PONTUAL', 'EXITO', name='naturezalancamento'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'AGUARDANDO_TRANSITO', 'CANCELADO', name='statuslancamento'), nullable=False),
    sa.Column('participante_id', sa.Uuid(), nullable=False),
    sa.Column('processo_id', sa.Uuid(), nullable=True),
    sa.Column('cartao_id', sa.Uuid(), nullable=True),
    sa.Column('centro_custo_id', sa.Uuid(), nullable=False),
    sa.Column('reembolsavel', sa.Boolean(), nullable=False),
    sa.Column('lancamento_pai_id', sa.Uuid(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(natureza != 'EXITO') OR (processo_id IS NOT NULL)", name='check_exito_requires_processo'),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartoes_credito.id'], ),
    sa.ForeignKeyConstraint(['centro_custo_id'], ['centros_custo.id'], ),
    sa.ForeignKeyConstraint(['lancamento_pai_id'], ['lancamentos.id'], ),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_processos_numero'), table_name='processos')
    op.drop_table('processos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_participantes_nome'), table_name='participantes')
    op.drop_index(op.f('ix_participantes_documento'), table_name='participantes')
    op.drop_table('participantes')
    op.drop_table('centros_custo')
    op.drop_table('cartoes_credito')
    op.drop_index(op.f('ix_audit_logs_tabela'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_registro_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
