"""Add_missing_models_and_update_existing_ones

Revision ID: 1d36cfc4968e
Revises: 
Create Date: 2026-02-25 10:01:19.020458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d36cfc4968e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartoes_credito',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('dia_fechamento', sa.Integer(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('limite', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('centros_custo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('secret_2fa', sa.String(length=64), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.add_column('lancamentos', sa.Column('valor_realizado', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('lancamentos', sa.Column('cartao_id', sa.Uuid(), nullable=True))
    op.add_column('lancamentos', sa.Column('centro_custo_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'lancamentos', 'cartoes_credito', ['cartao_id'], ['id'])
    op.create_foreign_key(None, 'lancamentos', 'centros_custo', ['centro_custo_id'], ['id'])
    op.add_column('processos', sa.Column('numero_cnj', sa.String(length=30), nullable=True))
    op.add_column('processos', sa.Column('percentual_exito', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_unique_constraint(None, 'processos', ['numero_cnj'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processos', type_='unique')
    op.drop_column('processos', 'percentual_exito')
    op.drop_column('processos', 'numero_cnj')
    op.drop_constraint(None, 'lancamentos', type_='foreignkey')
    op.drop_constraint(None, 'lancamentos', type_='foreignkey')
    op.drop_column('lancamentos', 'centro_custo_id')
    op.drop_column('lancamentos', 'cartao_id')
    op.drop_column('lancamentos', 'valor_realizado')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('centros_custo')
    op.drop_table('cartoes_credito')
    # ### end Alembic commands ###
