"""update_centro_custo

Revision ID: 6573520c1156
Revises: cd51a38de7af
Create Date: 2026-02-27 10:41:38.914554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6573520c1156'
down_revision: Union[str, Sequence[str], None] = 'cd51a38de7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_custo', sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA', name='tipolancamento'), nullable=True))
    op.add_column('centros_custo', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'centros_custo', 'centros_custo', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'centros_custo', type_='foreignkey')
    op.drop_column('centros_custo', 'parent_id')
    op.drop_column('centros_custo', 'tipo')
    # ### end Alembic commands ###
